/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.comm;

import  ui.comm.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CommProfile;
import model.CommHistory;


public class HospitalInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalInfoJPanel
     */

   CommHistory commHistory ;
    CommProfile commprofile;
    private JPanel userProcessContainer;
    CommProfile comm;
    public HospitalInfoJPanel(JPanel upc, CommProfile d) {
        initComponents();
         comm=d;
        userProcessContainer=upc;
        this.comm=comm;
        this.userProcessContainer=userProcessContainer;




//System.out.println("=============================");
//System.out.println("==///////////////////////////===");
//        jTextField9.setText(comm.getCommName());
//        jTextField10.setText(comm.getCommId());
//        jTextField11.setText(comm.getEmailAddress());
//        jTextField12.setText(comm.getAddress());
//        jTextField13.setText(comm.getHospital());
//        jTextField14.setText(comm.getPassword());
// 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        SaveBtn = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UploadBtn = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtCommName = new javax.swing.JTextField();
        txtCommID1 = new javax.swing.JTextField();
        txtEmailAddress = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtHospital = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Community:");

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(java.awt.Color.lightGray);
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("City:");

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Password:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Hospital:");

        SaveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Specialty:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Name:");

        UploadBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        UploadBtn.setText("Uplaod");
        UploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Photo:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("ID:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Email:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Infomation");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("Name:");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Address:");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("ID:");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("Email:");

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setText("Hospital:");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("Password:");

        txtCommName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommNameActionPerformed(evt);
            }
        });

        BtnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BackBtn.setText("<<Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel15)))
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(BackBtn)
                                .addGap(82, 82, 82)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCommName, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                .addComponent(txtCommID1)
                                .addComponent(txtEmailAddress)
                                .addComponent(txtAddress)
                                .addComponent(txtHospital)
                                .addComponent(txtPassword))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(BtnSave)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCommName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtCommID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(BtnSave)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void UploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UploadBtnActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void txtCommNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommNameActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed

// String CommName=null;
//        
//        try{
//            CommName=txtCommName.getText();
//            char[] arr=CommName.toCharArray();
//            if(arr.length==0){
//                JOptionPane.showMessageDialog(this, "The name cannot be null!");
//                return;
//            }
//            for(char c: arr){
//                if(!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))){
//                    JOptionPane.showMessageDialog(this, "The name should be alpha!");
//                    return;
//                }
//            }
//            for(CommProfile d:commHistory.getCommhistory()) {
//                if (commprofile.getCommName().equals(CommName)) {
//                    JOptionPane.showMessageDialog(this, "The name has been already been registered!");
//                    return;
//                }
//            }    
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Check the format of the name!");
//            return;
//        }

// String CommID=null;
//        try{
//            CommID=txtCommID1.getText();
//            char[] arr=CommID.toCharArray();
//            if(arr.length!=7){
//                JOptionPane.showMessageDialog(this, "The ID length should be 7!");
//                return;
//            }
//            if(CommID.matches("[0-9]*")==false){
//                JOptionPane.showMessageDialog(this, "The ID should only be numbers!");
//                return;
//            }
//            
//            for(CommProfile d:commHistory.getCommhistory()) {
//                if (commprofile.getCommId().equals(CommID)) {
//                    JOptionPane.showMessageDialog(this, "The ID is already used by other registers!");
//                    return;
//                }
//            }    
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Check the format of the id!");
//            return;
//        }
//
//
//String hospital=null;
//        try{
//            hospital=txtHospital.getText();
//           
//            if(hospital.length()==0){
//               JOptionPane.showMessageDialog(this, "Please input a hospital");
//                return; 
//            }
//             
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Check the format!");
//            return;
//        }
//
//String Address=null;
//        try{
//            Address=txtAddress.getText();
//           
//            if(Address.length()==0){
//               JOptionPane.showMessageDialog(this, "Please input a hospital");
//                return; 
//            }
//             
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Check the format!");
//            return;
//        }
//
//
// String EmailAddress=null;
//        try{
//            EmailAddress=txtEmailAddress.getText();
//           
//            if((EmailAddress.contains("@"))==false||EmailAddress.contains(".")==false){
//               JOptionPane.showMessageDialog(this, "Please input a correct email!");
//                return; 
//            }
//          
//            for(CommProfile d:commHistory.getCommhistory()) {
//                if (commprofile.getEmailAddress().equals(EmailAddress)) {
//                    JOptionPane.showMessageDialog(this, "The email has already been registered!");
//                    return;
//                }
//            }    
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Check the format!");
//            return;
//        }
//String Password=null;
//        try{
//            Password=txtPassword.getText();
//           
//            if(Password.length()==0){
//               JOptionPane.showMessageDialog(this, "Please input a password");
//                return; 
//            }
//             
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, "Check the format!");
//            return;
//        }



//
//        commprofile = commHistory.addProfile();
//        
//        commprofile.setCommName(txtCommName.getText());
//        commprofile.setCommId(txtCommID1.getText());
//        commprofile.setHospital(txtHospital.getText());
//        commprofile.setAddress(txtAddress.getText());
//        commprofile.setEmailAddress(txtEmailAddress.getText());
//        commprofile.setPassword(txtPassword.getText());
//
        JOptionPane.showMessageDialog(this,"Registered Successful");

        txtCommName.setText("");
        txtCommID1.setText("");
        txtHospital.setText("");
        txtAddress.setText("");
        txtEmailAddress.setText("");
        txtPassword.setText("");


        // TODO add your handling code here:
   ManageHospitalRecordJPanel mpcjp = new ManageHospitalRecordJPanel(userProcessContainer, comm);
        userProcessContainer.add("ManageHospitalRecordJPanel", mpcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
 
        
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton UploadBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCommID1;
    private javax.swing.JTextField txtCommName;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
