/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.comm;

import ui.comm.*;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import javax.swing.table.DefaultTableModel;
import model.CommProfile;
import model.UserHistory;
import model.UserProfile;
//import model.Encounter;
import model.HospitalHistory;
import model.HospitalProfile;


public class ManageHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatientsRecordJPanel
     */
    HospitalHistory HospitalHistory ;
    HospitalProfile hospitalProfile;
    private JPanel userProcessContainer;
    CommProfile comm;
    public ManageHospitalJPanel(JPanel upc, HospitalHistory hh) {
        initComponents();
        userProcessContainer=upc;
        HospitalHistory= hh;
        






    }
    
//    public void refreshTable() {
//
//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
//        model.setRowCount(0);
//
//        for (Encounter e : comm.getEncounterHistory().getEncounterhis()) {
//            Object row[] = new Object[3];
//            row[0] = e;
//            row[1] = e.getTemperature();
//            row[2] = e.getBloodPressure();
//            model.addRow(row);
//        }
//    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        jbtDelete1 = new javax.swing.JButton();
        jbtUpdateDate1 = new javax.swing.JButton();
        txtHospitalName = new javax.swing.JTextField();
        txtCommID = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BtnView = new javax.swing.JButton();
        ViewDetailBtn1 = new javax.swing.JButton();
        ViewDetailBtn2 = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Manage Hospital Records");

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HospitalName", "CommID", "EmailAddress", "Password", "Address"
            }
        ));
        jScrollPane1.setViewportView(tblHospital);

        jbtDelete1.setText("Delete");
        jbtDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDelete1ActionPerformed(evt);
            }
        });

        jbtUpdateDate1.setText("UpdateDate");
        jbtUpdateDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateDate1ActionPerformed(evt);
            }
        });

        txtHospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalNameActionPerformed(evt);
            }
        });

        txtCommID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommIDActionPerformed(evt);
            }
        });

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel2.setText("search");

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel10.setText("HospitalName:");

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel11.setText("CommID:");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setText("EmailAddress:");

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setText("Password:");

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel14.setText("Address:");

        BtnView.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BtnView.setText("View");
        BtnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewActionPerformed(evt);
            }
        });

        ViewDetailBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ViewDetailBtn1.setText("Attention Please !!!  ");
        ViewDetailBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailBtn1ActionPerformed(evt);
            }
        });

        ViewDetailBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ViewDetailBtn2.setText("Network issue, no more information display here!!");
        ViewDetailBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDetailBtn2ActionPerformed(evt);
            }
        });

        BtnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jButton1)
                            .addGap(170, 170, 170)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel14)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(BtnSave)
                                            .addGap(20, 20, 20)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtCommID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(4, 4, 4)
                                                    .addComponent(ViewDetailBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(145, 145, 145)
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(26, 26, 26)
                                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(4, 4, 4))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                            .addComponent(BtnView)
                                                            .addGap(33, 33, 33)))))
                                            .addComponent(ViewDetailBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(588, 588, 588)
                        .addComponent(jbtUpdateDate1)
                        .addGap(18, 18, 18)
                        .addComponent(jbtDelete1)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel14, jLabel15, jLabel17});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddress, txtCommID, txtEmail, txtHospitalName, txtPassword});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbtDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbtUpdateDate1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ViewDetailBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(ViewDetailBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtCommID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14))
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnView)
                            .addComponent(BtnSave))
                        .addGap(61, 61, 61))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel14, jLabel15, jLabel17});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtAddress, txtCommID, txtEmail, txtHospitalName, txtPassword});

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
//        String ss = txtSearch.getText();
//        search(ss);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jbtDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDelete1ActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblHospital.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        HospitalProfile se = (HospitalProfile) model.getValueAt(selectedRowIndex, 0);

        HospitalHistory.removeHospital(se);

        JOptionPane.showMessageDialog(this, "User Profile Deleted");

        populateHospitalTable();
    }//GEN-LAST:event_jbtDelete1ActionPerformed

    private void jbtUpdateDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateDate1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

        DefaultTableModel model=(DefaultTableModel)tblHospital.getModel();
        int row=tblHospital.getSelectedRow();

        if(txtHospitalName.getText().length()==0
            || txtCommID.getText().length()==0
            || txtEmail.getText().length()==0
            || txtPassword.getText().length()==0
            || txtAddress.getText().length()==0
            //|| txtspecialty.getText().length()==0
        ){
            JOptionPane.showMessageDialog(this, "Check the format!");
            return;
        }

        model.setValueAt(txtHospitalName.getText(), row, 0);
        model.setValueAt(txtCommID.getText(), row, 1);
        model.setValueAt(txtEmail.getText(), row, 2);
        model.setValueAt(txtPassword.getText(), row, 3);
        model.setValueAt(txtAddress.getText(), row, 4);

        txtHospitalName.setText("");
        txtCommID.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
        txtAddress.setText("");
    }//GEN-LAST:event_jbtUpdateDate1ActionPerformed

    private void txtHospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalNameActionPerformed

    private void txtCommIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommIDActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String ss = txtSearch.getText();
       HospitalHistory.searchHospital(ss,ss);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void BtnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewActionPerformed

//         String HospitalName=null;
//        
//                try{
//                        HospitalName=txtHospitalName.getText();
//                        char[] arr=HospitalName.toCharArray();
//                        if(arr.length==0){
//                                JOptionPane.showMessageDialog(this, "The name cannot be null!");
//                                return;
//                            }
//                        for(char c: arr){
//                                if(!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))){
//                                        JOptionPane.showMessageDialog(this, "The name should be alpha!");
//                                        return;
//                                    }
//                            }
//                        for(HospitalProfile d:HospitalHistory.getHospitalhistory()) {
//                                if (hospitalProfile.getHospitalName().equals(HospitalName)) {
//                                        JOptionPane.showMessageDialog(this, "The name has been already been registered!");
//                                        return;
//                                    }
//                            }
//                    }catch(Exception e){
//                        JOptionPane.showMessageDialog(null, "Check the format of the name!");
//                        return;
//                    }
//        //
//         String CommID=null;
//                try{
//                        CommID=txtCommID.getText();
//                        char[] arr=CommID.toCharArray();
//                        if(arr.length!=4){
//                                JOptionPane.showMessageDialog(this, "The ID length should be 4!");
//                                return;
//                            }
//                        if(CommID.matches("[0-9]*")==false){
//                                JOptionPane.showMessageDialog(this, "The ID should only be numbers!");
//                                return;
//                            }
//            
//                        for(HospitalProfile d:HospitalHistory.getHospitalhistory()) {
//                                if (hospitalProfile.getCommId().equals(CommID)) {
//                                        JOptionPane.showMessageDialog(this, "The ID is already used by other registers!");
//                                        return;
//                                    }
//                            }
//                    }catch(Exception e){
//                        JOptionPane.showMessageDialog(null, "Check the format of the id!");
//                        return;
//                    }
//        
//        
//         String EmailAddress=null;
//                try{
//                        EmailAddress=txtEmail.getText();
//            
//                        if((EmailAddress.contains("@"))==false||EmailAddress.contains(".")==false){
//                               JOptionPane.showMessageDialog(this, "Please input a correct email!");
//                                return;
//                            }
//          
//                          for(HospitalProfile d:HospitalHistory.getHospitalhistory()) {
//                                if (hospitalProfile.getEmailAddress().equals(EmailAddress)) {
//                                        JOptionPane.showMessageDialog(this, "The email has already been registered!");
//                                        return;
//                                    }
//                            }
//                    }catch(Exception e){
//                        JOptionPane.showMessageDialog(null, "Check the format!");
//                        return;
//                    }
//        String Password=null;
//                try{
//                        Password=txtPassword.getText();
//            
//                        if(Password.length()==0){
//                               JOptionPane.showMessageDialog(this, "Please input a password");
//                                return;
//                            }
//            
//                    }catch(Exception e){
//                        JOptionPane.showMessageDialog(null, "Check the format!");
//                        return;
//                    }
//        String Address=null;
//                try{
//                        Address=txtAddress.getText();
//            
//                        if(Address.length()==0){
//                               JOptionPane.showMessageDialog(this, "Please input a hospital");
//                                return;
//                            }
//            
//                    }catch(Exception e){
//                        JOptionPane.showMessageDialog(null, "Check the format!");
//                        return;
//                    }

        //
        //System.out.println("====111111111111=====");
 //      HospitalProfile  hospitalProfile = HospitalHistory.addProfile();
//        //System.out.println("========22222222222===========");
//
//        hospitalProfile.setHospitalName(txtHospitalName.getText());
//        hospitalProfile.setCommId(txtCommID.getText());
//        hospitalProfile.setAddress(txtAddress.getText());
//        hospitalProfile.setEmailAddress(txtPassword.getText());
//        hospitalProfile.setPassword(txtAddress.getText());
//        JOptionPane.showMessageDialog(this,"Saved Successful");
//        System.out.println(txtCommID.getText());
//        System.out.println("=========================");
//        txtHospitalName.setText("");
//        txtCommID.setText("");
//        txtAddress.setText("");
//        txtPassword.setText("");
//        txtAddress.setText("");

        // TODO add your handling code here:
//        ManageHospitalRecordJPanel mpcjp = new ManageHospitalRecordJPanel(userProcessContainer, hospitalHistory);
//        userProcessContainer.add("ManageHospitalRecordJPanel", mpcjp);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);

    }//GEN-LAST:event_BtnViewActionPerformed

    private void ViewDetailBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewDetailBtn1ActionPerformed

    private void ViewDetailBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDetailBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ViewDetailBtn2ActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
//populateHospitalTable();
    }//GEN-LAST:event_BtnSaveActionPerformed
    
    //public void search (String str){
    //    
    //    model = (DefaultTableModel) jTable1.getModel();
    //    TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
    //    jTable1.setRowSorter(trs);
    //    trs.setRowFilter(RowFilter.regexFilter(str,cmbsearch.getSelectedIndex()));
    //}
      private void populateHospitalTable(){
        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        model.setRowCount(0);
//        cmb  
        for (HospitalProfile ep :HospitalHistory.getHospitalhistory()) {
            Object[] row = new Object[5];
            
            row[0] = ep.getHospitalName();
            row[1] = ep.getCommId();
            row[2] = ep.getEmailAddress();
            row[3] = ep.getPassword();
            row[4] = ep.getAddress();
            model.addRow(row);
        }
        
        
     }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSave;
    private javax.swing.JButton BtnView;
    private javax.swing.JButton ViewDetailBtn1;
    private javax.swing.JButton ViewDetailBtn2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtDelete1;
    private javax.swing.JButton jbtUpdateDate1;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCommID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
