/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package doctor.UI;

import java.awt.CardLayout;
import javax.swing.JPanel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.DoctorHistory;
import model.DoctorProfile;

/**
 *
 * @author yongxingnie
 */
public class DoctorRegisterWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorRegisterWorkAreaJPanel
     */
    DoctorProfile doctor;
    DoctorHistory doctorDirectory;
    private JPanel userProcessContainer;
    private final JFileChooser openFileChooser;
    private BufferedImage img;
    
    public DoctorRegisterWorkAreaJPanel(JPanel upc, DoctorHistory ds) {
        initComponents();
        userProcessContainer=upc;
        doctorDirectory=ds;
        
        openFileChooser=new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("c:\\Desktop"));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UploadBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();

        UploadBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        UploadBtn.setText("Uplaod");
        UploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setText("Photo:");

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel9.setText("Email:");

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(java.awt.Color.lightGray);
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setText("Password:");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Sign Up as a Doctor!");

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setText("ID:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Community:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("City:");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Hospital:");

        SaveBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Specialty:");

        BackBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        BackBtn.setText("<<Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField7)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UploadBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField8))
                                        .addGap(80, 80, 80))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(SaveBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BackBtn)))
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(148, 148, 148)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(231, 231, 231)
                            .addComponent(jLabel1)))
                    .addContainerGap(288, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(BackBtn)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(UploadBtn)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(SaveBtn)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(376, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadBtnActionPerformed
        // TODO add your handling code here:
        
        int returnValue=openFileChooser.showOpenDialog(this);

        if(returnValue==JFileChooser.APPROVE_OPTION){
            try{
                img=ImageIO.read(openFileChooser.getSelectedFile());
                jLabel12=new JLabel(new ImageIcon(img));
                doctor.setPhoto(jLabel12.getIcon());
            }
            catch(Exception e){
                jLabel12.setText("Photo loading failed!");
            }
            jLabel12.setText("Photo upload successfully!");
        }else{
            jLabel12.setText("Please Choose a photo!");
        }
    }//GEN-LAST:event_UploadBtnActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        String name=null;
        
        try{
            name=jTextField1.getText();
            char[] arr=name.toCharArray();
            if(arr.length==0){
                JOptionPane.showMessageDialog(this, "The name cannot be null!");
                return;
            }
            for(char c: arr){
                if(!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))){
                    JOptionPane.showMessageDialog(this, "The name should be alpha!");
                    return;
                }
            }
            for(DoctorProfile d:doctorDirectory.getDoctorhistory()) {
                if (doctor.getName().equals(name)) {
                    JOptionPane.showMessageDialog(this, "The name has been already been registered!");
                    return;
                }
            }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format of the name!");
            return;
        }
        
        String id=null;
        try{
            id=jTextField2.getText();
            char[] arr=id.toCharArray();
            if(arr.length!=7){
                JOptionPane.showMessageDialog(this, "The ID length should be 7!");
                return;
            }
            if(id.matches("[0-9]*")==false){
                JOptionPane.showMessageDialog(this, "The ID should only be numbers!");
                return;
            }
            
            for(DoctorProfile d:doctorDirectory.getDoctorhistory()) {
                if (doctor.getID().equals(id)) {
                    JOptionPane.showMessageDialog(this, "The ID is already used by other registers!");
                    return;
                }
            }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format of the id!");
            return;
        }
        
        String email=null;
        try{
            email=jTextField3.getText();
           
            if((email.contains("@"))==false||email.contains(".")==false){
               JOptionPane.showMessageDialog(this, "Please input a correct email!");
                return; 
            }
          
            for(DoctorProfile d:doctorDirectory.getDoctorhistory()) {
                if (doctor.getEmail().equals(email)) {
                    JOptionPane.showMessageDialog(this, "The email has already been registered!");
                    return;
                }
            }    
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format!");
            return;
        }
        
        String hospital=null;
        try{
            hospital=jTextField4.getText();
           
            if(hospital.length()==0){
               JOptionPane.showMessageDialog(this, "Please input a hospital");
                return; 
            }
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format!");
            return;
        }
        
        String Specialty=null;
        try{
            Specialty=jTextField5.getText();
           
            if(Specialty.length()==0){
               JOptionPane.showMessageDialog(this, "Please input a Specialty");
                return; 
            }
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format!");
            return;
        }
        
        String Community=null;
        try{
            Community=jTextField6.getText();
           
            if(Community.length()==0){
               JOptionPane.showMessageDialog(this, "Please input a Community");
                return; 
            }
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format!");
            return;
        }
        
        String city=null;
        try{
            city=jTextField7.getText();
           
            if(city.length()==0){
               JOptionPane.showMessageDialog(this, "Please input a city");
                return; 
            }
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format!");
            return;
        }
        
        String password=null;
        try{
            password=jTextField8.getText();
           
            if(password.length()==0){
               JOptionPane.showMessageDialog(this, "Please input a password");
                return; 
            }
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Check the format!");
            return;
        }
        
        doctor=doctorDirectory.addProfile();
        
        doctor.setName(jTextField1.getText());
        doctor.setID(jTextField2.getText());
        doctor.setEmail(jTextField3.getText());
        doctor.setHospital(jTextField4.getText());
        doctor.setSpecialty(jTextField5.getText());
        doctor.setCommunity(jTextField6.getText());
        doctor.setCity(jTextField7.getText());
        doctor.setPassword(jTextField8.getText());
        doctor.setPhoto(jLabel12.getIcon());

        JOptionPane.showMessageDialog(this, "Registration Successfully!");

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jLabel12.setIcon(null);

    }//GEN-LAST:event_SaveBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton UploadBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
